// Marvel Rivals roster for the daily guessing game.
// To add a hero: copy a line, edit it, keep the comma. Fields:
//   name, gender ("Male"/"Female"/"Duo"), roles [], teams [], origin, year
const HEROES = [
  {"name": "Doctor Strange", "gender": "Male", "roles": ["Vanguard"], "teams": ["Avengers", "Defenders", "Illuminati"], "origin": "Earth", "year": 2024},
  {"name": "Hulk", "gender": "Male", "roles": ["Vanguard"], "teams": ["Avengers", "Defenders"], "origin": "Earth", "year": 2024},
  {"name": "Iron Man", "gender": "Male", "roles": ["Duelist"], "teams": ["Avengers", "Illuminati"], "origin": "Earth", "year": 2024},
  {"name": "Spider-Man", "gender": "Male", "roles": ["Duelist"], "teams": ["Avengers", "Spider-Verse"], "origin": "Earth", "year": 2024},
  {"name": "Luna Snow", "gender": "Female", "roles": ["Strategist"], "teams": ["Agents of Atlas"], "origin": "Earth", "year": 2024},
  {"name": "Namor", "gender": "Male", "roles": ["Duelist"], "teams": ["Defenders", "Illuminati"], "origin": "Earth", "year": 2024},
  {"name": "Loki", "gender": "Male", "roles": ["Strategist"], "teams": ["Asgardians", "Villains"], "origin": "Asgard", "year": 2024},
  {"name": "Black Panther", "gender": "Male", "roles": ["Duelist"], "teams": ["Avengers", "Wakanda"], "origin": "Earth", "year": 2024},
  {"name": "Magik", "gender": "Female", "roles": ["Duelist"], "teams": ["X-Men", "Mutants", "New Mutants"], "origin": "Earth", "year": 2024},
  {"name": "Rocket Raccoon", "gender": "Male", "roles": ["Strategist"], "teams": ["Guardians of the Galaxy"], "origin": "Halfworld", "year": 2024},
  {"name": "Groot", "gender": "Male", "roles": ["Vanguard"], "teams": ["Guardians of the Galaxy"], "origin": "Planet X", "year": 2024},
  {"name": "Peni Parker", "gender": "Female", "roles": ["Vanguard"], "teams": ["Spider-Verse"], "origin": "Earth", "year": 2024},
  {"name": "Storm", "gender": "Female", "roles": ["Duelist"], "teams": ["X-Men", "Mutants", "Avengers"], "origin": "Earth", "year": 2024},
  {"name": "Magneto", "gender": "Male", "roles": ["Vanguard"], "teams": ["Mutants", "Brotherhood", "Villains"], "origin": "Earth", "year": 2024},
  {"name": "Star-Lord", "gender": "Male", "roles": ["Duelist"], "teams": ["Guardians of the Galaxy"], "origin": "Earth", "year": 2024},
  {"name": "Mantis", "gender": "Female", "roles": ["Strategist"], "teams": ["Guardians of the Galaxy"], "origin": "Earth", "year": 2024},
  {"name": "The Punisher", "gender": "Male", "roles": ["Duelist"], "teams": ["Marvel Knights"], "origin": "Earth", "year": 2024},
  {"name": "Scarlet Witch", "gender": "Female", "roles": ["Duelist"], "teams": ["Avengers", "Mutants"], "origin": "Earth", "year": 2024},
  {"name": "Hela", "gender": "Female", "roles": ["Duelist"], "teams": ["Asgardians", "Villains"], "origin": "Asgard", "year": 2024},
  {"name": "Venom", "gender": "Male", "roles": ["Vanguard"], "teams": ["Symbiotes", "Spider-Verse"], "origin": "Klyntar", "year": 2024},
  {"name": "Adam Warlock", "gender": "Male", "roles": ["Strategist"], "teams": ["Guardians of the Galaxy"], "origin": "Earth", "year": 2024},
  {"name": "Thor", "gender": "Male", "roles": ["Vanguard"], "teams": ["Avengers", "Asgardians"], "origin": "Asgard", "year": 2024},
  {"name": "Jeff the Land Shark", "gender": "Male", "roles": ["Strategist"], "teams": ["Agents of Atlas"], "origin": "Earth", "year": 2024},
  {"name": "Winter Soldier", "gender": "Male", "roles": ["Duelist"], "teams": ["Avengers", "Thunderbolts"], "origin": "Earth", "year": 2024},
  {"name": "Captain America", "gender": "Male", "roles": ["Vanguard"], "teams": ["Avengers"], "origin": "Earth", "year": 2024},
  {"name": "Psylocke", "gender": "Female", "roles": ["Duelist"], "teams": ["X-Men", "Mutants", "X-Force"], "origin": "Earth", "year": 2024},
  {"name": "Moon Knight", "gender": "Male", "roles": ["Duelist"], "teams": ["Marvel Knights", "Avengers"], "origin": "Earth", "year": 2024},
  {"name": "Hawkeye", "gender": "Male", "roles": ["Duelist"], "teams": ["Avengers"], "origin": "Earth", "year": 2024},
  {"name": "Squirrel Girl", "gender": "Female", "roles": ["Duelist"], "teams": ["Avengers"], "origin": "Earth", "year": 2024},
  {"name": "Iron Fist", "gender": "Male", "roles": ["Duelist"], "teams": ["Defenders", "Marvel Knights"], "origin": "Earth", "year": 2024},
  {"name": "Black Widow", "gender": "Female", "roles": ["Duelist"], "teams": ["Avengers", "S.H.I.E.L.D."], "origin": "Earth", "year": 2024},
  {"name": "Cloak & Dagger", "gender": "Duo", "roles": ["Strategist"], "teams": ["Marvel Knights", "Defenders"], "origin": "Earth", "year": 2024},
  {"name": "Wolverine", "gender": "Male", "roles": ["Duelist"], "teams": ["X-Men", "Mutants", "Avengers"], "origin": "Earth", "year": 2024},
  {"name": "Mister Fantastic", "gender": "Male", "roles": ["Duelist"], "teams": ["Fantastic Four", "Illuminati"], "origin": "Earth", "year": 2025},
  {"name": "Invisible Woman", "gender": "Female", "roles": ["Strategist"], "teams": ["Fantastic Four"], "origin": "Earth", "year": 2025},
  {"name": "Human Torch", "gender": "Male", "roles": ["Duelist"], "teams": ["Fantastic Four"], "origin": "Earth", "year": 2025},
  {"name": "The Thing", "gender": "Male", "roles": ["Vanguard"], "teams": ["Fantastic Four"], "origin": "Earth", "year": 2025},
  {"name": "Emma Frost", "gender": "Female", "roles": ["Vanguard"], "teams": ["X-Men", "Mutants", "Villains"], "origin": "Earth", "year": 2025},
  {"name": "Ultron", "gender": "Male", "roles": ["Strategist"], "teams": ["Villains", "Avengers"], "origin": "Earth", "year": 2025},
  {"name": "Phoenix", "gender": "Female", "roles": ["Duelist"], "teams": ["X-Men", "Mutants"], "origin": "Earth", "year": 2025},
  {"name": "Blade", "gender": "Male", "roles": ["Duelist"], "teams": ["Marvel Knights", "Midnight Sons"], "origin": "Earth", "year": 2025},
  {"name": "Angela", "gender": "Female", "roles": ["Vanguard"], "teams": ["Asgardians", "Guardians of the Galaxy"], "origin": "Heven", "year": 2025},
  {"name": "Daredevil", "gender": "Male", "roles": ["Duelist"], "teams": ["Defenders", "Marvel Knights"], "origin": "Earth", "year": 2025},
  {"name": "Gambit", "gender": "Male", "roles": ["Strategist"], "teams": ["X-Men", "Mutants"], "origin": "Earth", "year": 2025},
  {"name": "Rogue", "gender": "Female", "roles": ["Vanguard"], "teams": ["X-Men", "Mutants", "Avengers"], "origin": "Earth", "year": 2025},
  {"name": "Deadpool", "gender": "Male", "roles": ["Duelist", "Vanguard", "Strategist"], "teams": ["Mutants", "X-Force"], "origin": "Earth", "year": 2026},
  {"name": "Elsa Bloodstone", "gender": "Female", "roles": ["Duelist"], "teams": ["Midnight Sons"], "origin": "Earth", "year": 2026},
  {"name": "White Fox", "gender": "Female", "roles": ["Strategist"], "teams": ["Agents of Atlas"], "origin": "Earth", "year": 2026},
  {"name": "Black Cat", "gender": "Female", "roles": ["Duelist"], "teams": ["Spider-Verse", "Villains"], "origin": "Earth", "year": 2026},
  {"name": "Devil Dinosaur", "gender": "Male", "roles": ["Vanguard"], "teams": ["Unaffiliated"], "origin": "Earth", "year": 2026},
  {"name": "Cyclops", "gender": "Male", "roles": ["Duelist"], "teams": ["X-Men", "Mutants"], "origin": "Earth", "year": 2026},
  {"name": "Jubilee", "gender": "Female", "roles": ["Strategist"], "teams": ["X-Men", "Mutants"], "origin": "Earth", "year": 2026},
  {"name": "The Hood", "gender": "Male", "roles": ["Vanguard"], "teams": ["Villains"], "origin": "Earth", "year": 2026},
  {"name": "Gorr the God Butcher", "gender": "Male", "roles": ["Duelist"], "teams": ["Villains"], "origin": "Other World", "year": 2026}
];
